"""로그온 자동 기동 — 시작프로그램 폴더의 런처 .bat 생성/제거.

작업 스케줄러를 쓰지 않는 이유(설계): 창 하나를 띄우는 데 XML 등록 인프라를
들일 필요가 없고, 시작프로그램 폴더는 **관리자 권한이 필요 없으며 사람이 눈으로
확인·제거할 수 있다**(작업 관리자 '시작프로그램' 탭에도 표준으로 잡힌다).

런처는 **생성물**이다 — `--auto on` 시점의 파이썬·프로그램 폴더 절대경로를 박아
넣는다. 실행 시점에 탐색하지 않는 이유는 I-A7: 이 PC는 탐색 사슬이 git 작업
트리를 고르므로(DSYNC_HOME 미설정 + C:\\dooraydrive 부재), 반쯤 고친 코드가
하루 종일 실계정에 도는 사고가 실재한다.

**순수 ASCII로 쓴다** — cmd가 .bat을 콘솔 코드페이지(한국어 Windows에서 CP949)로
읽어 UTF-8 한글을 잘못 쪼갠다(2026-08-04 실측). 한국어 메시지는 python이 낸다.
"""
from __future__ import annotations

import os
import sys
import winreg
from pathlib import Path

from ..util.paths import ext_path

__all__ = ["startup_dir", "launcher_path", "install", "remove", "describe",
           "disable_quickedit", "LAUNCHER_NAME"]

LAUNCHER_NAME = "dooray-sync-loop.bat"

_SHELL_FOLDERS = r"Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders"
_APPROVED = (r"Software\Microsoft\Windows\CurrentVersion\Explorer"
             r"\StartupApproved\StartupFolder")


def startup_dir() -> Path:
    """현재 사용자의 시작프로그램 폴더.

    레지스트리의 Shell Folders\\Startup이 정본이다 — 폴더 리디렉션(기업 환경에서
    흔하다)이 걸려 있으면 %APPDATA% 기준 조립이 틀린 경로를 만든다.
    """
    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, _SHELL_FOLDERS) as key:
            value, _ = winreg.QueryValueEx(key, "Startup")
            if value:
                return Path(os.path.expandvars(str(value)))
    except OSError:
        pass
    base = os.environ.get("APPDATA") or str(Path.home() / "AppData" / "Roaming")
    return Path(base) / "Microsoft" / "Windows" / "Start Menu" / "Programs" / "Startup"


def launcher_path() -> Path:
    return startup_dir() / LAUNCHER_NAME


def _repo_root() -> Path:
    """이 파일 기준의 프로그램 폴더(= 패키지의 부모)."""
    return Path(__file__).resolve().parent.parent.parent


def _python_exe() -> str:
    """등록 시점의 파이썬 절대경로. pythonw가 아니라 python이어야 한다 —
    보이는 창이 목적이다. 어떤 이유로 비면 PATH의 python으로 떨어진다."""
    exe = sys.executable or ""
    if exe.lower().endswith("pythonw.exe"):
        cand = exe[:-len("pythonw.exe")] + "python.exe"
        if os.path.exists(ext_path(cand)):
            return cand
    return exe or "python"


def _render(repo: Path, python_exe: str) -> str:
    """런처 .bat 본문. ASCII 전용, 경로에 공백이 있어도 안전하게 인용한다.

    자기 자신을 최소화로 한 번 다시 띄우는 구조인 이유: Explorer는 시작프로그램
    폴더의 .bat을 항상 보통 창으로 띄우고 '최소화로 실행' 속성이 없다(.lnk에만
    있는데 그건 COM 없이 만들기 번거롭다). 매일 아침 창이 화면 한복판에 뜨면
    성가셔서 언젠가 시작프로그램을 꺼 버린다 — 작업 표시줄에만 있게 한다.
    """
    return (
        "@echo off\r\n"
        "REM ==========================================================\r\n"
        "REM  GENERATED by: synchere.bat --auto on\r\n"
        "REM  Do not edit. Re-run '--auto on' to regenerate,\r\n"
        "REM  '--auto off --all' to remove.\r\n"
        "REM  Paths are pinned at registration time on purpose:\r\n"
        "REM  the loop must not search for the program folder.\r\n"
        "REM ==========================================================\r\n"
        "if not \"%~1\"==\"run\" (\r\n"
        f"  start \"Dooray Sync\" /min \"%~f0\" run\r\n"
        "  exit /b\r\n"
        ")\r\n"
        "title Dooray Sync\r\n"
        "set \"PYTHONUTF8=1\"\r\n"
        "set \"PYTHONIOENCODING=utf-8\"\r\n"
        f"set \"PYTHONPATH={repo}\"\r\n"
        f"\"{python_exe}\" -P -m dooray_sync.auto\r\n"
        "if errorlevel 1 (\r\n"
        "  echo.\r\n"
        "  echo [STOP] The sync loop exited with an error. Press any key to close.\r\n"
        "  pause >nul\r\n"
        ")\r\n"
    )


def install() -> tuple[bool, str]:
    """런처를 시작프로그램 폴더에 쓴다. (성공, 사유)."""
    dest = launcher_path()
    try:
        os.makedirs(ext_path(dest.parent), exist_ok=True)
        body = _render(_repo_root(), _python_exe())
        # ASCII 전용 자기 검증 — 한글이 섞이면 CP949 파서가 깨진다.
        body.encode("ascii")
        with open(ext_path(dest), "w", encoding="ascii", newline="") as f:
            f.write(body)
    except (OSError, UnicodeEncodeError) as exc:
        return False, f"{type(exc).__name__}: {exc}"
    return True, str(dest)


def remove() -> tuple[bool, str]:
    dest = launcher_path()
    try:
        os.remove(ext_path(dest))
    except FileNotFoundError:
        return True, "등록되어 있지 않았습니다"
    except OSError as exc:
        return False, f"{type(exc).__name__}: {exc}"
    return True, str(dest)


def _approval() -> str | None:
    """작업 관리자에서 '사용 안 함'으로 꺼졌는지. None이면 판정 정보 없음.

    StartupApproved 값은 12바이트 바이너리이고 첫 바이트의 bit0이 서면 비활성이다
    (02/06=사용, 03/07=사용 안 함). 이 조용한 비활성화를 못 보면 "켰는데 안 돈다"의
    원인을 영원히 못 찾는다.
    """
    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, _APPROVED) as key:
            data, _ = winreg.QueryValueEx(key, LAUNCHER_NAME)
    except OSError:
        return None
    if not isinstance(data, bytes) or not data:
        return None
    return "disabled" if data[0] & 1 else "enabled"


def describe() -> tuple[bool, str]:
    """(등록됨, 사람이 읽는 설명). 읽기 전용 — 네트워크 없음."""
    dest = launcher_path()
    if not os.path.exists(ext_path(dest)):
        return False, "등록 안 됨 (synchere.bat --auto on 으로 등록)"
    state = _approval()
    if state == "disabled":
        return True, (f"등록됨이지만 **사용 안 함** 상태입니다 — 작업 관리자 > "
                      f"시작 프로그램에서 'Dooray Sync'를 사용으로 바꾸세요 ({dest})")
    return True, f"등록됨{' (사용)' if state == 'enabled' else ''} — {dest}"


def disable_quickedit() -> bool:
    """콘솔의 QuickEdit을 끈다.

    켜져 있으면 창 안을 실수로 **클릭하는 순간 프로세스가 멈춘다**(아무 키나 누를
    때까지). 창은 멀쩡해 보이는데 동기화는 죽어 있는, 이 방식의 가장 조용한
    실패 모드다. 레지스트리를 건드리지 않고 이 콘솔에만 적용한다.
    """
    try:
        import ctypes

        kernel32 = ctypes.windll.kernel32          # type: ignore[attr-defined]
        handle = kernel32.GetStdHandle(-10)        # STD_INPUT_HANDLE
        mode = ctypes.c_uint32()
        if not kernel32.GetConsoleMode(handle, ctypes.byref(mode)):
            return False
        enable_quick_edit = 0x0040
        enable_extended_flags = 0x0080
        # EXTENDED_FLAGS를 함께 세우지 않으면 QuickEdit 해제가 적용되지 않는다.
        new_mode = (mode.value & ~enable_quick_edit) | enable_extended_flags
        return bool(kernel32.SetConsoleMode(handle, new_mode))
    except Exception:      # noqa: BLE001 — 콘솔이 없거나 리다이렉트된 환경
        return False
